agriculture:
  farming:
    parts: 2
    requirements:
      "minecraft:wheat_seeds":
        amount: [8, 16, 32]
      "minecraft:dirt":
        amount: [64, 128, 256]
      "minecraft:carrot":
        amount: [0, 4, 32]
        scaling: false
      "minecraft:potato":
        amount: [0, 4, 32]
        scaling: false
      "minecraft:beetroot_seeds":
        amount: [0, 0, 16]
        scaling: false
  plant_cooking:
    parts: 2
    requirements:
      "minecraft:wheat":
        amount: [4, 8, 16]
      "minecraft:carrot":
        amount: [8, 16, 32]
      "minecraft:potato":
        amount: [8, 16, 32]
      "minecraft:beetroot":
        amount: [0, 8, 16]
      "minecraft:pumpkin":
        amount: [0, 4, 8]
      "minecraft:melon":
        amount: [0, 0, 2]
  advanced_cooking:
    parts: 1
    requirements:
      "minecraft:bread": 
        amount: [8, 16, 32]
      "minecraft:baked_potato":
        amount: [16, 32, 64]
      "minecraft:gold_ingot": 
        amount: [8, 16, 32]
      "minecraft:pumpkin_pie": 
        amount: [0, 2, 4]
      "minecraft:golden_apple": 
        amount: [0, 0, 1]
        scaling: false
  taming:
    parts: 1
    requirements:
      "minecraft:wheat":
        amount: [4, 8, 16]
      "minecraft:carrot":
        amount: [8, 12, 16]
      "minecraft:potato":
        amount: [8, 12, 16]
      "minecraft:saddle":
        amount: [0, 0, 1]
        scaling: false
  breeding:
    parts: 2
    requirements: 
      "minecraft:wheat_seeds":
        amount: [4, 16, 32]
      "minecraft:wheat":
        amount: [4, 16, 32]
      "minecraft:potato":
        amount: [4, 16, 32]
      "minecraft:carrot":
        amount: [4, 16, 32]
  meet_cooking:
    parts: 2
    "minecraft:beef":
      amount: [4, 8, 16]
    "minecraft:chicken":
      amount: [4, 8, 16]
    "minecraft:porkchop":
      amount: [4, 8, 16]
    "#minecraft:coals":
      amount: [8, 16, 32]
    "minecraft:rabbit":
      amount: [0, 0, 2]
      scaling: false
  beekeeping:
    parts: 1
    requirements:
      "minecraft:dandelion":
        amount: [1, 2, 4]
      "minecraft:poppy":
        amount: [1, 2, 4]
  fishing:
    parts: 1
    requirements:
      "minecraft:string":
        amount: [0, 2, 4]
      "#minecraft:fishes":
        amount: [2, 8, 16]
      "minecraft:stick":
        amount: [16, 32, 64]

combat: 
  leather_armor: # armor & shields: bones, gunpowder, slimeballs; weapons: rotten flesh, spider eyes, string, arrows 
    parts: 1
    requirements:
      "minecraft:leather":
        amount: [2, 4, 8]       
  chainmail_armor:
    parts: 2
    requirements:
      "minecraft:bone": 
        amount: [2, 4, 8]
      "minecraft:iron_nugget":
        amount: [16, 32, 64]
  iron_armor:
    parts: 2
    requirements:
      "minecraft:iron_ingot": 
        amount: [4, 16, 32]
      "minecraft:bone": 
        amount: [2, 4, 8]
      "minecraft:gunpowder":
        amount: [0, 0, 2]
  diamond_armor:
    parts: 3
    requirements:
      "minecraft:diamond": 
        amount: [3, 4, 8]
      "minecraft:gunpowder":
        amount: [0, 2, 4]
      "minecraft:slime_ball":
        amount: [0, 0, 4]
  shields:
    parts: 3
    requirements:
      "minecraft:iron_ingot":
        amount: [4, 8, 16]
      "#minecraft:planks":
        amount: [32, 64, 128]
      "minecraft:bone":
        amount: [0, 2, 4]
      "minecraft:gunpowder":
        amount: [0, 0, 2]
  swords:
    parts: 2
    requirements:
      "#minecraft:planks":
        amount: [16, 32, 64]
      "minecraft:rotten_flesh":
        amount: [0, 2, 8]
      "minecraft:spider_eye":
        amount: [0, 0, 2]
  ranged_weapons:
    parts: 2
    requirements:
      "minecraft:flint":
        amount: [8, 16, 32]
      "minecraft:stick":
        amount: [16, 32, 64]
      "minecraft:arrow":
        amount: [0, 2, 8]
      "minecraft:bow":
        amount: [0, 0, 1]
        scaling: false
  
processing:
  brick_smelting:
    parts: 1
    requirements:
      "#minecraft:stone_crafting_materials":
        amount: [32, 64, 128]
      "minecraft:clay_ball":
        amount: [8, 16, 32]
      "#minecraft:coals":
        amount: [16, 32, 64]
  glass_smelting:
    parts: 1
    requirements:
      "#minecraft:coals":
        amount: [8, 16, 32]
      "minecraft:sand":
        amount: [64, 128, 256]
  ore_processing:
    parts: 3
    requirements:
      "#minecraft:coals":
        amount: [16, 32, 64]
      "minecraft:raw_iron":
        amount: [8, 16, 32]
      "minecraft:raw_copper":
        amount: [16, 32, 64]
  colors:
    parts: 1
    requirements:
      "minecraft:dandelion":
        amount: [1, 2, 4]
      "minecraft:poppy":
        amount: [1, 2, 4]
      "minecraft:lapis_lazuli":
        amount: [0, 4, 8]
  stone_working:
    parts: 1
    requirements:
      "minecraft:cobblestone":
        amount: [64, 128, 256]
      "minecraft:andesite":
        amount: [16, 32, 64]
      "minecraft:diorite":
        amount: [16, 32, 64]
      "minecraft:granite":
        amount: [16, 32, 64]
      "minecraft:cobbled_deepslate":
        amount: [16, 32, 64]
  wood_working:
    parts: 1
    requirements:
      "#minecraft:logs":
        amount: [32, 64, 128]
      "minecraft:wooden_axe":
        amount: [1, 2, 4]

technology:
  basic_redstone:
    parts: 2
    requirements:
      "minecraft:redstone":
        amount: [16, 32, 64]
      "minecraft:iron_ingot":
        amount: [8, 16, 32]
      "#minecraft:planks":
        amount: [16, 32, 64]
      "minecraft:slime_ball":
        amount: [0, 0, 2]
  boat:
    parts: 1
    requirements:
      "#minecraft:planks":
        amount: [32, 64, 128]
      "#minecraft:fishes":
        amount: [0, 0, 2]
  boat_with_chest:
    parts: 2
    requirements:
      "#minecraft:planks":
        amount: [32, 64, 128]
      "minecraft:chest":
        amount: [1, 2, 4]
      "#minecraft:boats":
        amount: [1, 2, 4]
  fire_and_gunpowder:
    parts: 1
    requirements:
      "#minecraft:coals":
        amount: [8, 16, 32]
      "minecraft:flint":
        amount: [8, 16, 32]
      "minecraft:gunpowder":
        amount: [0, 4, 8]
      "minecraft:paper":
        amount: [16, 32, 64]
  minecarts:
    parts: 2
    requirements:
      "minecraft:iron_ingot":
        amount: [16, 32, 64]
      "minecraft:redstone":
        amount: [16, 32, 64]
      "minecraft:stick":
        amount: [32, 64, 128]
  minecarts_increased_speed_1:
    parts: 1
    requirements:
      "minecraft:gold_ingot":
        amount: [8, 16, 32]
      "minecraft:redstone":
        amount: [16, 32, 64]
      "minecraft:rail":
        amount: [16, 32, 64]
      "minecraft:minecart":
        amount: [1, 2, 4]
  minecarts_increased_speed_2:
    parts: 2
    requirements:
      "minecraft:diamond":
        amount: [4, 8, 16]
      "minecraft:redstone":
        amount: [32, 64, 128]
      "minecraft:rail":
        amount: [32, 64, 128]
      "minecraft:minecart":
        amount: [1, 2, 4]
  writing:
    parts: 1
    requirements:
      "#minecraft:planks":
        amount: [16, 32, 64]
      "minecraft:sugar_cane":
        amount: [16, 32, 64]
      "minecraft:ink_sac":
        amount: [0, 4, 8]
      "minecraft:book":
        amount: [0, 0, 1]
        scaling: false

tools:
  torch:
    parts: 1
    requirements:
      "#minecraft:coals":
        amount: [8, 16, 32]
      "minecraft:stick":
        amount: [16, 32, 64]
  ladder:
    parts: 1
    requirements:
      "minecraft:stick":
        amount: [64, 128, 256]
  stone_tools:
    parts: 4
    requirements:
      "#minecraft:stone_tool_materials":
        amount: [64, 128, 256]
      "minecraft:stick":
        amount: [64, 128, 256]
  iron_tools:
    parts: 4
    requirements:
      "minecraft:iron_ingot":
        amount: [32, 64, 128]
      "minecraft:stick":
        amount: [64, 128, 256]
  diamond_tools:
    parts: 4
    requirements:
      "minecraft:diamond":
        amount: [4, 8, 16]
      "minecraft:stick":
        amount: [64, 128, 256]
  furnace:
    parts: 1
    requirements:
      "#minecraft:stone_crafting_materials":
        amount: [32, 64, 128]
  furnace_upgrades:
    parts: 2
    requirements:
      "minecraft:iron_ingot":
        amount: [16, 32, 64]
      "minecraft:smooth_stone":
        amount: [32, 64, 128]
      "minecraft:furnace":
        amount: [1, 2, 4]
      "minecraft:copper_ingot":
        amount: [16, 32, 64]
  furnace_speed_upgrades:
    parts: 2
    requirements:
      "minecraft:gold_ingot":
        amount: [16, 32, 64]
      "minecraft:dried_kelp":
        amount: [8, 16, 32]
      "minecraft:smooth_stone":
        amount: [64, 128, 256]
      "minecraft:cooked_beef":
        amount: [0, 4, 8]
      "minecraft:glass":
        amount: [16, 32, 64]
  smithing:
    parts: 4
    requirements:
      "minecraft:iron_ingot":
        amount: [32, 64, 128]
      "#minecraft:coals":
        amount: [16, 32, 64]
      "minecraft:smithing_table":
        amount: [0, 0, 1]
        scaling: false
  compass:
    parts: 1
    requirements:
      "minecraft:iron_ingot":
        amount: [4, 8, 16]
      "minecraft:redstone":
        amount: [8, 16, 32]
      "minecraft:compass":
        amount: [0, 0, 1]
        scaling: false
  configurable_compass:
    parts: 1
    requirements:
      "minecraft:iron_ingot":
        amount: [4, 8, 16]
      "minecraft:chiseled_stone_bricks":
        amount: [32, 64, 128]
      "minecraft:echo_shard":
        amount: [0, 0, 1]
  map:
    parts: 1
    requirements:
      "minecraft:paper":
        amount: [16, 32, 64]
      "minecraft:compass":
        amount: [1, 2, 4]
      "minecraft:map":
        amount: [0, 0, 1]
        scaling: false
  shears:
    parts: 1
    requirements:
      "minecraft:iron_ingot":
        amount: [4, 8, 16]
      "#minecraft:wool":
        amount: [0, 4, 8]
  loom:
    parts: 1
    requirements:
      "#minecraft:planks":
        amount: [16, 32, 64]
      "#minecraft:wool":
        amount: [8, 16, 32]
      "minecraft:string":
        amount: [0, 4, 8]
  storage:
    parts: 2
    requirements:
      "minecraft:chest":
        amount: [1, 2, 4]
      "#minecraft:planks":
        amount: [16, 32, 64]
      "#minecraft:wooden_slabs":
        amount: [8, 16, 32]
  bundle:
    parts: 1
    requirements:
      "minecraft:leather":
        amount: [4, 8, 16]
      "minecraft:string":
        amount: [4, 8, 16]
      
  