combat:
  combat: null
  leather_armor:
    parts: 2
    requirements:
      "minecraft:cobblestone":
        amount: [32, 64, 128]
        scaling: true
      "minecraft:leather":
        amount: [16, 32, 64]
        scaling: true
  chainmail_armor:
    requirements:
      "minecraft:iron_ingot": 16
  iron_armor:
    requirements:
      "minecraft:iron_ingot": 64
tools:
  tools: null
  torch:
    count: 1
    requirements:
      "minecraft:coal": 32
      "minecraft:stick": 128
  ladder:
    requirements:
      "minecraft:stick": 256
  stone_tools:
    count: 4
    requirements:
      "minecraft:cobblestone": 1024
      "minecraft:stick": 256